language: node_js
node_js:
 - "node"
install:
 - npm ci
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm test
    - stage: build
      script: npm run build
stages:
  - lint
  - test
  - build
after_success: "npm run coveralls"
