language: node_js
node_js:
  - node
install:
  - npm ci
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm test
    - stage: build
      script: npm run build
      deploy:
        provider: npm
        email: tanfonto@pm.me
        api_key:
          secure: H+cZAUMdrfyETdWJ77j1jvzyQhsZhnHdULoZef5geXB/1U/c73yHaOPgeEkRQki+Jwn9E6PuQMMsqStDfvG5L4Vbvz8ZIvYFZbaU+REs5DorwHJWwrQICw+MMq8iiplG3JzBnBsxBSJIVQjV+NruhVBMJhMlJgT64uXh+vT6a4N/bmuXyHkq5Oi/KoGVLJe/kH8nycLntDv2VNJz6PKzH/c4SLJoBYq7EadEgW3mI4Feb06sexVIUQadcgUhnBqNZWQ9fJTrL021cGgCXSqSjp2WKGr8KR+/W6VmJ1MAr5pC1R8ZpLUBzXnVU7ASURUjQZWfygqe82bOh3MNEaqI01+aEhjWWt51eZq7OU6joWmgluvBzt5tDXs9Kq3/aNzJlehRe9gfmBLMtb6b1sZCUUpl/5Gw6bPTlXd/zVDUWLByfmu/3X6Z5IPSSydXBDyWf5StaIOsCzVtb69EQu29yz5O6hC51powip/Nb+hOIrFu1nRsTB1R7C98e6gS9GJSh7OJ7TvkEaDO50kuOk8mkWypMbjsC5wxZfoAFSARc/R9Rsmmf8kU30roctWFM6+0CZoqqk0/XEJX1fIKL6xR4px7i9QZ2I9qERVJDgIAT8R6pFYW6qgNRJCi4fhOpxb+1mOJS8KO0ebZgyn2oTawVcVfvMw677R349Y88WjaikA=
          on:
            tags: true
            repo: tanfonto/storx
